export { default as restaurants } from './reducers/restaurants.reducer'
export { default as selectedRestaurant } from './reducers/selectedRestaurant.reducer'
export { default as coords } from './reducers/coords.reducer'
export { default as router } from './reducers/router.reducer'
export { default as previewedRestaurant } from './reducers/previewedRestaurant.reducer'
export { default as menu } from './reducers/menu.reducer'
export { default as cart } from './reducers/cart.reducer'
