export { default as restaurants } from './reducers/restaurants.reducer'
export { default as selectedRestaurant } from './reducers/selectedRestaurant.reducer'
export { default as coords } from './reducers/coords.reducer'
export { default as mapHeight } from './reducers/mapHeight.reducer'
export { default as router } from './reducers/router.reducer'
export { default as previewedRestaurant } from './reducers/previewedRestaurant.reducer'
