export enum ReduxActionType {
  SELECT_RESTAURANT = 'SELECT_RESTAURANT',
  SET_COORDS = 'SET_COORDS',
  SET_MAP_HEIGHT = 'SET_MAP_HEIGHT',
  GO_TO = 'GO_TO',
  PREVIEW_RESTAURANT = 'PREVIEW_RESTAURANT',
  SELECT_RESTAURANT_BY_SLUG = 'SELECT_RESTAURANT_BY_SLUG'
}
