export enum ReduxActionType {
  SELECT_RESTAURANT = 'SELECT_RESTAURANT',
  SET_COORDS = 'SET_COORDS',
  SET_MAP_HEIGHT = 'SET_MAP_HEIGHT',
  GO_TO = 'GO_TO',
  PREVIEW_RESTAURANT = 'PREVIEW_RESTAURANT',
  SELECT_RESTAURANT_BY_SLUG = 'SELECT_RESTAURANT_BY_SLUG',
  RESET_PREVIEW_RESTAURANT = 'RESET_PREVIEW_RESTAURANT',
  RESET_SELECT_RESTAURANT = 'RESET_SELECT_RESTAURANT',
  ADD_TO_CART = 'ADD_TO_CART',
  OPEN_CART = 'OPEN_CART',
  CLOSE_CART = 'CLOSE_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART'
}
